# Generated by Django 3.1.7 on 2021-03-26 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.basemodel')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
            bases=('post.basemodel',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='post.basemodel')),
                ('title', models.CharField(max_length=100)),
                ('image', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('content_img', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d')),
                ('comment', models.TextField(blank=True, null=True)),
                ('post_url', models.URLField()),
                ('country', models.CharField(choices=[('K', '국내'), ('W', '해외')], max_length=2)),
                ('category', models.ManyToManyField(to='post.Category')),
                ('like_user_set', models.ManyToManyField(blank=True, related_name='like_user_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Post',
                'ordering': ['-id'],
            },
            bases=('post.basemodel',),
        ),
    ]
